// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mageumoyukdexmfucqrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZ2V1bW95dWtkZXhtZnVjcXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDI4ODUsImV4cCI6MjA2MzUxODg4NX0.fgFmH9V4JW7ePZ5aRQI3pNVr48pfDWlOI5lUvE60WSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);